package problems;

import utils.MathUtil;

/**
 * Even Fibonacci numbers.
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be: 
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * 
 * @author Jake Holden - jholden88@live.co.uk
 *
 */
public class Problem2 extends Problem
{
	protected void solve() 
	{
		System.out.println("The sum of the even valued terms of the Fibonacci sequence that do not exceed four million is " + sumOfAllEvenFibonacci());
	}
	
	private long sumOfAllEvenFibonacci()
	{
		long sum = 0;
		int x = 2;
		int y = 1;
		int n = 0;
		
		while (x <= 4000000)
		{
			if (MathUtil.isEven(x))
			{
				sum += x;
			}
			
			n = y;
			y = x;
			x += n;
		}
		
		return sum;
	}
}
